import type { PortfolioDetail } from "@/lib/types";

// 실제 시공 사례 사진/데이터 입고 전까지 사용하는 샘플 데이터입니다.
export const portfolioDetails: PortfolioDetail[] = [
  {
    slug: "suwon-corporate-stage",
    title: "수원 기업행사 무대·LED·음향 통합 설치",
    metaTitle: "수원 기업행사 무대 설치 사례 | LED·음향·조명 통합 구성 | LORD",
    metaDescription:
      "수원에서 진행된 기업 창립기념식 무대·LED·음향·조명 통합 설치 사례입니다. 짧은 설치 시간과 전기 용량 제약을 해결한 구성을 확인하세요.",
    region: "경기도 수원시",
    venue: "호텔 연회장",
    eventType: "기업 창립기념식",
    attendees: "약 300명",
    items: "무대, 백월, LED 전광판, 음향, 조명",
    scale: "가로 8m × 세로 4m",
    installTime: "약 5시간",
    operationScope: "설치, 리허설, 행사 운영, 철거",
    challenge: "짧은 설치 시간, 전기 용량 제한, 발표자 동선 구성",
    categories: ["stage", "led", "sound", "corporate"],
    overview:
      "창립기념식을 앞둔 기업 고객이 행사 당일 오전에만 설치 시간을 확보할 수 있는 상황에서, 브랜드 로고가 들어간 백월과 LED 전광판, 음향·조명을 하나의 팀이 통합 시공한 사례입니다.",
    clientRequest:
      "발표 자료와 영상이 선명하게 보이는 LED 화면, 브랜드 로고가 강조된 백월, 시상식 진행에 무리 없는 무대 동선을 요청했습니다.",
    siteConditions:
      "호텔 연회장 특성상 천고가 제한적이었고, 행사 전날 다른 행사가 예정되어 있어 당일 오전 설치만 가능했습니다. 전기 용량도 기존 콘센트 기준으로 제한적이었습니다.",
    proposedConfig: [
      "가로 8m × 세로 4m 무대 + 계단 2개소",
      "브랜드 로고 적용 백월 + LED 전광판 동시 구성",
      "무선 마이크 4채널 + 스피커 2조",
      "발표자·시상자 동선을 고려한 무대 폭 설계",
    ],
    equipmentSpecs: [
      { item: "무대", spec: "가로 8m × 세로 4m × 높이 60cm" },
      { item: "LED", spec: "가로 5m × 세로 2.8m, 실내 사양" },
      { item: "음향", spec: "스피커 2조, 무선 마이크 4채널, 믹서 1대" },
      { item: "조명", spec: "무대 조명 8조, 백월 조명 4조" },
    ],
    processSteps: [
      "사전 협의 — 브랜드 가이드와 발표 자료 형식 확인",
      "현장 실사 — 전기 용량, 반입 동선 확인",
      "당일 오전 설치 — 약 5시간",
      "리허설 — 발표 자료 송출, 음향 점검",
      "행사 운영 — 시상식 진행 지원",
      "당일 철거",
    ],
    similarRecommendation:
      "비슷한 호텔 연회장 행사라면 LED 크기와 전기 용량을 사전에 확인하는 것이 중요합니다. 발표 자료 중심 행사라면 LED를, 브랜드 노출이 중요하면 백월 비중을 높이는 방식으로 구성을 조정할 수 있습니다.",
    faq: [
      { q: "비슷한 행사도 같은 구성으로 설치할 수 있나요?", a: "네, 행사장 천고와 전기 용량이 비슷하다면 동일한 구성을 기준으로 빠르게 제안드릴 수 있습니다." },
      { q: "이 사례와 비슷한 견적을 받을 수 있나요?", a: "행사 규모와 LED 포함 여부가 같다면 비슷한 범위의 견적을 안내드릴 수 있습니다. 정확한 견적은 현장 확인 후 제공됩니다." },
    ],
    relatedLinks: [
      { label: "기업행사 무대", href: "/stage-rental-installation/corporate-event-stage" },
      { label: "LED 전광판", href: "/system-equipment-rental/led-screen" },
      { label: "기업행사 솔루션", href: "/event-solutions/corporate-event" },
    ],
  },
  {
    slug: "osan-memorial-stage",
    title: "오산 추도식 무대·백월 설치",
    metaTitle: "오산 추도식 무대 설치 사례 | 백월·음향 구성 | LORD",
    metaDescription: "오산에서 진행된 공공기관 추도식 무대·백월 설치 사례입니다. 차분한 디자인 톤과 헌화 동선 구성을 확인하세요.",
    region: "경기도 오산시",
    venue: "공공기관 광장",
    eventType: "추도식",
    attendees: "약 150명",
    items: "무대, 백월, 음향",
    scale: "가로 6m × 세로 3m",
    installTime: "약 3시간",
    operationScope: "설치, 행사 운영, 철거",
    challenge: "차분한 디자인 톤 유지, 헌화 동선 확보",
    categories: ["stage", "public"],
    overview: "지역 공공기관이 주최한 추도식에서, 과한 장식 없이 행사의 의미를 살리는 무대와 백월을 설치한 사례입니다.",
    clientRequest: "행사의 엄숙함을 해치지 않는 절제된 디자인과, 헌화·묵념 진행에 무리가 없는 동선을 요청했습니다.",
    siteConditions: "공공기관 광장으로 평탄한 지면이었으나, 헌화대와 무대 사이 이동 동선 확보가 중요했습니다.",
    proposedConfig: [
      "가로 6m × 세로 3m 단색 무대",
      "행사명만 표기한 절제된 백월 디자인",
      "헌화대-무대 간 이동 동선 확보",
      "차분한 음향 진행(묵념용 무음향 구간 포함)",
    ],
    equipmentSpecs: [
      { item: "무대", spec: "가로 6m × 세로 3m × 높이 40cm" },
      { item: "백월", spec: "가로 6m × 세로 2.4m, 무광 출력" },
      { item: "음향", spec: "스피커 1조, 유선 마이크 2채널" },
    ],
    processSteps: ["사전 협의 — 행사 진행 순서 확인", "현장 실사", "설치 — 약 3시간", "행사 운영 지원", "당일 철거"],
    similarRecommendation: "추도식·기념식류 행사는 백월 디자인을 단순화하고 동선 확보를 우선하는 구성이 적합합니다.",
    faq: [
      { q: "포트폴리오에 없는 행사도 가능한가요?", a: "네, 공공행사·추모행사 경험을 바탕으로 비슷한 톤의 구성을 제안드릴 수 있습니다." },
      { q: "현장 실사 후 제안 받을 수 있나요?", a: "가능합니다. 추도식과 같이 동선과 분위기가 중요한 행사는 현장 실사를 권장합니다." },
    ],
    relatedLinks: [
      { label: "기념식·추도식 솔루션", href: "/event-solutions/ceremony-memorial-stage" },
      { label: "음향", href: "/system-equipment-rental/sound" },
    ],
  },
  {
    slug: "brand-popup-photozone",
    title: "브랜드 팝업스토어 포토존 제작",
    metaTitle: "브랜드 팝업스토어 포토존 제작 사례 | 오브제·조명 구성 | LORD",
    metaDescription: "서울 브랜드 팝업스토어 포토존 제작 사례입니다. 좁은 공간 활용과 SNS 촬영 동선 설계를 확인하세요.",
    region: "서울특별시",
    venue: "팝업스토어 매장 내부",
    eventType: "브랜드 팝업스토어",
    attendees: "일일 방문객 약 200명",
    items: "포토존, 오브제, 조명, 사인물",
    scale: "가로 4m × 세로 3m",
    installTime: "약 6시간 (제작 포함)",
    operationScope: "제작, 설치, 운영 기간 중 유지보수, 철거 및 폐기",
    challenge: "좁은 공간 활용, SNS 촬영 동선 설계",
    categories: ["photozone", "corporate"],
    overview: "2주간 운영되는 브랜드 팝업스토어 내부에 방문객이 자연스럽게 촬영하고 공유할 수 있는 포토존을 제작한 사례입니다.",
    clientRequest: "브랜드 컬러를 반영한 오브제와, 좁은 매장 공간에서도 촬영이 가능한 동선을 요청했습니다.",
    siteConditions: "매장 면적이 협소해 포토존 크기를 최소화하면서도 시각적 임팩트를 유지해야 했습니다.",
    proposedConfig: [
      "가로 4m × 세로 3m 브랜드 오브제 포토존",
      "벽면 조명으로 공간 확장감 부여",
      "입구-포토존-출구 단방향 동선 설계",
      "SNS 해시태그 사인물 배치",
    ],
    equipmentSpecs: [
      { item: "오브제", spec: "브랜드 컬러 맞춤 제작, 높이 2.2m" },
      { item: "조명", spec: "벽면 라인 조명 + 포인트 스폿 조명" },
      { item: "사인물", spec: "해시태그 안내 사인 2개소" },
    ],
    processSteps: ["디자인 시안 협의", "오브제 제작", "현장 설치 — 약 6시간", "운영 기간 중 유지보수", "철거 및 폐기"],
    similarRecommendation: "짧은 운영 기간의 팝업스토어는 제작형보다 렌탈형 오브제를 활용하면 비용과 제작 기간을 줄일 수 있습니다.",
    faq: [
      { q: "사진 속 장비 구성을 변경할 수 있나요?", a: "네, 브랜드 컬러와 오브제 형태는 자유롭게 변경해 제작할 수 있습니다." },
      { q: "비슷한 견적을 받을 수 있나요?", a: "매장 면적과 운영 기간이 비슷하다면 유사한 범위의 견적을 안내드릴 수 있습니다." },
    ],
    relatedLinks: [
      { label: "팝업스토어 포토존", href: "/photozone-rental-production/popup-store-photozone" },
      { label: "브랜드 포토존", href: "/photozone-rental-production/brand-photozone" },
    ],
  },
  {
    slug: "hwaseong-outdoor-festival-stage",
    title: "화성 야외 축제 무대·트러스·음향 설치",
    metaTitle: "화성 야외 축제 무대 설치 사례 | 트러스·음향·LED 구성 | LORD",
    metaDescription: "화성 지역축제 야외 무대·트러스·음향·LED 설치 사례입니다. 우천 대비와 강풍 대응 구성을 확인하세요.",
    region: "경기도 화성시",
    venue: "야외 광장",
    eventType: "지역축제",
    attendees: "약 2,000명",
    items: "무대, 트러스, 음향, 조명, LED",
    scale: "가로 10m × 세로 6m",
    installTime: "약 8시간",
    operationScope: "설치, 리허설, 행사 운영(2일), 철거",
    challenge: "우천 대비, 강풍 대응, 출연자 동선 확보",
    categories: ["stage", "truss", "sound", "festival"],
    overview: "2일간 진행되는 지역축제에서 다수의 공연팀이 출연하는 대형 야외 무대를 트러스와 LED, 음향·조명 시스템으로 통합 구성한 사례입니다.",
    clientRequest: "여러 공연팀의 빠른 무대 전환과, 우천 시에도 공연이 중단되지 않는 안전한 구성을 요청했습니다.",
    siteConditions: "지면이 평탄했지만 일교차가 크고 강풍 가능성이 있는 야외 광장으로, 방수·고정 작업이 중요했습니다.",
    proposedConfig: [
      "가로 10m × 세로 6m 대형 무대 + 트러스 지붕 구조",
      "방수 LED + 출력 보강된 야외용 음향",
      "백스테이지 동선과 대기 공간 분리",
      "강풍 대비 트러스 고정 보강",
    ],
    equipmentSpecs: [
      { item: "무대", spec: "가로 10m × 세로 6m × 높이 1m" },
      { item: "트러스", spec: "지붕형 트러스, 하중 보강 적용" },
      { item: "음향", spec: "야외용 스피커 4조, 모니터 스피커 2조" },
      { item: "LED", spec: "가로 6m × 세로 3.4m, 방수 사양" },
    ],
    processSteps: [
      "사전 협의 — 출연팀 수, 진행 순서 확인",
      "현장 실사 — 지면, 전기, 기상 예보 확인",
      "설치 — 약 8시간",
      "리허설 — 출연팀별 음향·조명 점검",
      "2일간 행사 운영",
      "철거",
    ],
    similarRecommendation: "다수 출연팀이 있는 축제는 무대 폭을 넉넉히 잡고 백스테이지 동선을 분리하는 것이 전환 시간을 줄이는 핵심입니다.",
    faq: [
      { q: "비슷한 행사도 같은 구성으로 설치할 수 있나요?", a: "네, 참석 규모와 출연팀 수가 비슷하면 동일한 구성을 기준으로 제안드릴 수 있습니다." },
      { q: "현장 실사 후 제안 받을 수 있나요?", a: "야외 대형 무대는 기상 조건과 지면 상태 확인이 중요해 현장 실사를 권장합니다." },
    ],
    relatedLinks: [
      { label: "야외 무대", href: "/stage-rental-installation/outdoor-stage" },
      { label: "트러스/레이어", href: "/system-equipment-rental/truss-layer" },
      { label: "축제·공연 솔루션", href: "/event-solutions/festival-performance" },
    ],
  },
  {
    slug: "yongin-groundbreaking-stage",
    title: "용인 준공식 무대·테이프커팅존 설치",
    metaTitle: "용인 준공식 무대 설치 사례 | 테이프커팅존·의전 동선 구성 | LORD",
    metaDescription: "용인 산업단지 준공식 무대와 테이프커팅존 설치 사례입니다. 공사 현장 바닥 조건과 의전 동선 구성을 확인하세요.",
    region: "경기도 용인시",
    venue: "산업단지 공사 현장",
    eventType: "준공식",
    attendees: "약 100명",
    items: "무대, 테이프커팅존, 음향, 포토존",
    scale: "가로 6m × 세로 3m",
    installTime: "약 4시간",
    operationScope: "설치, 행사 운영, 철거",
    challenge: "공사 현장 고르지 않은 바닥, 내빈 의전 동선",
    categories: ["stage", "public"],
    overview: "산업단지 준공을 기념하는 행사에서, 평탄하지 않은 공사 현장 바닥에 무대와 테이프커팅존을 안전하게 설치한 사례입니다.",
    clientRequest: "내빈 다수가 참석하는 만큼 의전 동선을 명확히 하고, 테이프커팅 장면이 잘 보이는 구도를 요청했습니다.",
    siteConditions: "공사 현장 특유의 고르지 않은 바닥과 자재 적재 공간으로 인해 설치 위치 선정이 까다로웠습니다.",
    proposedConfig: [
      "바닥 수평 보강 후 가로 6m 무대 설치",
      "테이프커팅존과 내빈석 동선 분리",
      "포토존을 테이프커팅존 인근에 배치",
      "유선 음향으로 안정적인 진행",
    ],
    equipmentSpecs: [
      { item: "무대", spec: "가로 6m × 세로 3m, 수평 보강 다리 적용" },
      { item: "음향", spec: "스피커 1조, 유선 마이크 2채널" },
      { item: "포토존", spec: "가로 3m 백월형 포토존" },
    ],
    processSteps: ["현장 실사 — 바닥 상태, 자재 적재 위치 확인", "수평 보강 작업", "설치 — 약 4시간", "행사 운영", "철거"],
    similarRecommendation: "공사 현장 행사는 사전 현장 실사로 바닥 상태를 반드시 확인하고 수평 보강 시간을 일정에 포함해야 합니다.",
    faq: [
      { q: "공사 현장처럼 바닥이 고르지 않은 곳도 가능한가요?", a: "네, 수평 보강 작업을 통해 안전하게 설치할 수 있습니다. 사전 현장 확인을 권장합니다." },
    ],
    relatedLinks: [
      { label: "준공식·기공식 솔루션", href: "/event-solutions/groundbreaking-completion-ceremony" },
      { label: "야외 무대", href: "/stage-rental-installation/outdoor-stage" },
    ],
  },
  {
    slug: "incheon-awards-photowall",
    title: "인천 시상식 포토월·레드카펫 설치",
    metaTitle: "인천 시상식 포토월 설치 사례 | 레드카펫·로고 패턴 구성 | LORD",
    metaDescription: "인천에서 진행된 시상식 포토월·레드카펫 설치 사례입니다. 협찬사 로고 반복 패턴과 촬영 조명 구성을 확인하세요.",
    region: "인천광역시",
    venue: "컨벤션센터",
    eventType: "시상식",
    attendees: "약 200명",
    items: "포토월, 레드카펫, 조명, 차단봉",
    scale: "가로 6m × 세로 3m",
    installTime: "약 3시간",
    operationScope: "디자인, 출력, 설치, 행사 운영, 철거",
    challenge: "다수 협찬사 로고 배치, 촬영 조명 품질",
    categories: ["photozone", "lighting", "corporate"],
    overview: "다수의 협찬사가 참여한 시상식에서, 로고 반복 패턴 포토월과 레드카펫을 설치해 수상자 촬영 품질을 높인 사례입니다.",
    clientRequest: "10개 이상의 협찬사 로고를 균형 있게 배치하고, 촬영 시 그림자가 생기지 않는 조명을 요청했습니다.",
    siteConditions: "컨벤션센터 로비 공간으로 천장 조명이 충분하지 않아 별도 촬영 조명이 필요했습니다.",
    proposedConfig: [
      "가로 6m × 세로 3m 로고 반복 패턴 포토월",
      "레드카펫 + 차단봉으로 동선 정리",
      "양측 촬영 조명으로 그림자 최소화",
      "협찬사 로고 크기 균등 배치",
    ],
    equipmentSpecs: [
      { item: "포토월", spec: "가로 6m × 세로 3m, 로고 반복 패턴 출력" },
      { item: "조명", spec: "촬영용 조명 2조, 좌우 대칭 배치" },
      { item: "부속", spec: "레드카펫 6m, 차단봉 4조" },
    ],
    processSteps: ["로고 배치 시안 협의", "출력 및 구조물 제작", "설치 — 약 3시간", "행사 운영", "철거"],
    similarRecommendation: "협찬사가 많은 시상식은 로고 크기와 배치 규칙을 사전에 정해야 디자인 시안 수정 횟수를 줄일 수 있습니다.",
    faq: [
      { q: "로고 반복 패턴 제작이 가능한가요?", a: "네, 협찬사 로고 수와 우선순위를 알려주시면 균형 있는 반복 패턴으로 제작합니다." },
    ],
    relatedLinks: [
      { label: "포토월·백월", href: "/photozone-rental-production/photowall-backwall" },
      { label: "조명", href: "/system-equipment-rental/lighting" },
    ],
  },
  {
    slug: "seongnam-sports-day-stage",
    title: "성남 체육대회 본부석·시상무대·음향 설치",
    metaTitle: "성남 체육대회 무대 설치 사례 | 본부석·시상무대·음향 구성 | LORD",
    metaDescription: "성남 지역 체육대회 본부석·시상무대·음향 설치 사례입니다. 운동장 진행자 음향과 시상 동선 구성을 확인하세요.",
    region: "경기도 성남시",
    venue: "공공 운동장",
    eventType: "체육대회",
    attendees: "약 1,000명",
    items: "본부석, 시상무대, 음향, 포토존",
    scale: "가로 5m × 세로 3m (본부석), 가로 4m (시상무대)",
    installTime: "약 5시간",
    operationScope: "설치, 행사 운영(1일), 철거",
    challenge: "넓은 운동장 음성 전달, 시상 동선, 관객 안전",
    categories: ["stage", "sound", "sports"],
    overview: "지역 체육대회에서 본부석과 별도의 시상무대를 구성하고, 넓은 운동장 전체에 음성이 고르게 전달되도록 음향을 설계한 사례입니다.",
    clientRequest: "운동장 끝까지 진행 안내가 들리도록 하고, 시상식 때 단체사진 촬영이 가능한 무대를 요청했습니다.",
    siteConditions: "트랙이 있는 공공 운동장으로 스피커 배치 간격과 관중 동선 확보가 중요했습니다.",
    proposedConfig: [
      "본부석 무대 + 분리된 시상무대 구성",
      "운동장 양끝에 스피커 분산 배치",
      "시상무대 주변 안전선 설치",
      "기념촬영용 포토존 인근 배치",
    ],
    equipmentSpecs: [
      { item: "본부석", spec: "가로 5m × 세로 3m" },
      { item: "시상무대", spec: "가로 4m × 세로 2m" },
      { item: "음향", spec: "분산형 스피커 4조, 무선 마이크 2채널" },
    ],
    processSteps: ["현장 실사 — 운동장 규모, 스피커 배치 검토", "설치 — 약 5시간", "행사 운영(1일)", "철거"],
    similarRecommendation: "운동장 규모의 행사는 스피커를 한 곳에 집중하기보다 분산 배치해야 음성 전달력이 균일해집니다.",
    faq: [
      { q: "체육대회 진행용 음향만 렌탈할 수 있나요?", a: "네, 본부석·시상무대 없이 음향 장비만 별도로 렌탈하는 것도 가능합니다." },
      { q: "운동장에 무대 설치가 가능한가요?", a: "가능합니다. 트랙이나 잔디 상태에 맞춰 바닥 보호 장비를 함께 사용합니다." },
    ],
    relatedLinks: [
      { label: "체육대회 및 BJ 무대설치 솔루션", href: "/event-solutions/sports-broadcast-stage" },
      { label: "음향", href: "/system-equipment-rental/sound" },
    ],
  },
  {
    slug: "bundang-live-commerce-set",
    title: "분당 라이브커머스 방송 세트 제작",
    metaTitle: "분당 라이브커머스 방송 세트 제작 사례 | 조명·배경 구성 | LORD",
    metaDescription: "분당 스튜디오에서 진행된 라이브커머스 방송 세트 제작 사례입니다. 카메라 구도와 조명 설계를 확인하세요.",
    region: "경기도 성남시 분당구",
    venue: "방송 스튜디오",
    eventType: "라이브커머스 방송",
    attendees: "스튜디오 진행 인원 약 10명",
    items: "배경 세트, 조명, 소품, 음향",
    scale: "가로 5m × 세로 3m",
    installTime: "약 4시간",
    operationScope: "디자인, 제작, 설치, 방송 당일 지원",
    challenge: "카메라 구도에 맞춘 배경 설계, 제품이 잘 보이는 조명",
    categories: ["photozone", "lighting", "broadcast"],
    overview: "정기적으로 라이브커머스 방송을 진행하는 브랜드를 위해 카메라 구도와 제품 진열을 고려한 배경 세트와 조명을 제작한 사례입니다.",
    clientRequest: "제품 색감이 왜곡되지 않는 조명과, 여러 카메라 앵글에서도 어색하지 않은 배경을 요청했습니다.",
    siteConditions: "기존 스튜디오 공간이 협소해 세트와 조명 장비 배치를 효율적으로 구성해야 했습니다.",
    proposedConfig: [
      "가로 5m × 세로 3m 모듈형 배경 세트",
      "제품 진열대와 카메라 앵글 사전 시뮬레이션",
      "색온도 보정 조명 적용",
      "음향 노이즈 최소화 처리",
    ],
    equipmentSpecs: [
      { item: "배경 세트", spec: "모듈형, 가로 5m × 세로 3m" },
      { item: "조명", spec: "색온도 보정 조명 4조" },
      { item: "음향", spec: "방송용 마이크 2채널" },
    ],
    processSteps: ["카메라 구도 시뮬레이션", "세트 디자인 및 제작", "설치 — 약 4시간", "방송 당일 현장 지원"],
    similarRecommendation: "정기 방송용 세트는 모듈형으로 제작하면 다음 방송 때 일부 구성만 교체해 재사용할 수 있습니다.",
    faq: [
      { q: "BJ 방송용 배경 세트도 제작하나요?", a: "네, 개인방송·라이브커머스 모두 카메라 구도에 맞춘 배경 세트 제작이 가능합니다." },
      { q: "라이브커머스 촬영용 조명도 가능한가요?", a: "가능합니다. 제품 색감 왜곡을 줄이는 색온도 보정 조명을 적용합니다." },
    ],
    relatedLinks: [
      { label: "체육대회 및 BJ 무대설치 솔루션", href: "/event-solutions/sports-broadcast-stage" },
      { label: "조명", href: "/system-equipment-rental/lighting" },
    ],
  },
  {
    slug: "anyang-brand-launch-photozone",
    title: "안양 신제품 출시 브랜드 포토존",
    metaTitle: "안양 신제품 출시 포토존 제작 사례 | 브랜드 체험존 구성 | LORD",
    metaDescription: "안양에서 진행된 신제품 출시 행사 브랜드 포토존 제작 사례입니다. 제품 전시와 SNS 확산을 고려한 구성을 확인하세요.",
    region: "경기도 안양시",
    venue: "복합쇼핑몰 행사장",
    eventType: "신제품 출시 행사",
    attendees: "일일 방문객 약 500명",
    items: "포토존, 제품 전시대, 조명, 사인물",
    scale: "가로 5m × 세로 4m",
    installTime: "약 5시간",
    operationScope: "디자인, 제작, 설치, 운영 기간 중 점검, 철거",
    challenge: "제품 전시와 포토존 동선 통합, SNS 확산 유도",
    categories: ["photozone", "corporate"],
    overview: "복합쇼핑몰에서 진행된 신제품 출시 행사에서, 제품 전시와 포토존을 한 공간에 통합해 방문객의 체험과 촬영을 동시에 유도한 사례입니다.",
    clientRequest: "제품을 직접 체험하고 그 자리에서 바로 촬영할 수 있는 동선과, SNS 업로드를 유도하는 디자인을 요청했습니다.",
    siteConditions: "쇼핑몰 내 유동 인구가 많은 통로형 공간으로, 동선이 막히지 않도록 설계해야 했습니다.",
    proposedConfig: [
      "가로 5m × 세로 4m 체험형 포토존",
      "제품 전시대와 포토존 동선 일체화",
      "브랜드 컬러 조명 적용",
      "SNS 해시태그 사인물 배치",
    ],
    equipmentSpecs: [
      { item: "포토존", spec: "가로 5m × 세로 4m, 체험형 오브제 포함" },
      { item: "조명", spec: "브랜드 컬러 적용 조명 3조" },
      { item: "사인물", spec: "SNS 해시태그 안내 사인 2개소" },
    ],
    processSteps: ["디자인 시안 협의", "제작", "설치 — 약 5시간", "운영 기간 중 점검", "철거"],
    similarRecommendation: "유동 인구가 많은 쇼핑몰 행사는 포토존을 통로와 분리하면서도 시선이 닿는 위치에 배치하는 것이 효과적입니다.",
    faq: [
      { q: "제품을 함께 전시할 수 있나요?", a: "네, 포토존과 제품 전시대를 함께 구성해 체험과 촬영을 동시에 유도할 수 있습니다." },
      { q: "SNS 인증샷용 포토존도 제작하나요?", a: "가능합니다. 해시태그 유도 사인물과 함께 촬영하기 좋은 구도로 설계합니다." },
    ],
    relatedLinks: [
      { label: "브랜드 포토존", href: "/photozone-rental-production/brand-photozone" },
      { label: "기업행사 포토존", href: "/photozone-rental-production/corporate-photozone" },
    ],
  },
  {
    slug: "pyeongtaek-university-festival-stage",
    title: "평택 대학축제 공연무대·LED·조명 설치",
    metaTitle: "평택 대학축제 무대 설치 사례 | LED·조명 통합 구성 | LORD",
    metaDescription: "평택 대학교 축제 공연무대·LED·조명 설치 사례입니다. 다수 공연팀 진행과 야간 조명 연출 구성을 확인하세요.",
    region: "경기도 평택시",
    venue: "대학교 운동장",
    eventType: "대학축제",
    attendees: "약 1,500명",
    items: "무대, LED, 조명, 음향",
    scale: "가로 9m × 세로 5m",
    installTime: "약 7시간",
    operationScope: "설치, 리허설, 행사 운영(야간 포함), 철거",
    challenge: "다수 공연팀 빠른 전환, 야간 조명 연출",
    categories: ["stage", "led", "lighting", "festival"],
    overview: "낮부터 야간까지 이어지는 대학축제에서, 시간대별로 달라지는 조명 연출과 다수 공연팀의 빠른 무대 전환을 지원한 사례입니다.",
    clientRequest: "야간에는 화려한 조명 연출이 가능하고, 공연팀이 많아 무대 전환이 빠르게 이루어지길 요청했습니다.",
    siteConditions: "대학교 운동장으로 야간 행사를 위한 별도 조명 계획과 전기 용량 확보가 필요했습니다.",
    proposedConfig: [
      "가로 9m × 세로 5m 무대 + LED 배경 화면",
      "낮/야간 조명 시나리오 분리 설계",
      "백스테이지 공간으로 공연팀 대기 동선 분리",
      "야간 발전기 추가 배치",
    ],
    equipmentSpecs: [
      { item: "무대", spec: "가로 9m × 세로 5m" },
      { item: "LED", spec: "가로 6m × 세로 3.4m" },
      { item: "조명", spec: "무빙라이트 8조, 무대 조명 6조" },
      { item: "음향", spec: "공연용 스피커 4조, 모니터 스피커 2조" },
    ],
    processSteps: [
      "사전 협의 — 공연팀 순서, 야간 일정 확인",
      "현장 실사 — 전기, 조명 계획",
      "설치 — 약 7시간",
      "리허설",
      "야간 포함 행사 운영",
      "철거",
    ],
    similarRecommendation: "낮/야간을 모두 포함하는 축제는 조명 시나리오를 시간대별로 분리해 설계하면 연출 만족도가 높아집니다.",
    faq: [
      { q: "대학축제 무대 설치도 가능한가요?", a: "네, 대학축제처럼 다수 공연팀이 참여하는 행사 경험이 많습니다." },
      { q: "공연 리허설까지 지원하나요?", a: "가능합니다. 공연팀별 음향·조명 리허설을 진행 순서에 맞춰 지원합니다." },
    ],
    relatedLinks: [
      { label: "공연·축제 무대", href: "/stage-rental-installation/festival-performance-stage" },
      { label: "LED 전광판", href: "/system-equipment-rental/led-screen" },
      { label: "축제·공연 솔루션", href: "/event-solutions/festival-performance" },
    ],
  },
];

export const portfolioSamples = portfolioDetails;

export function getPortfolioBySlug(slug: string) {
  return portfolioDetails.find((item) => item.slug === slug);
}
